use Query Builder to CRUD for tasks
st-tramle/laravel-intern-2111 pull request #2
Opened 2021-12-21 15:48 UTC by st-tramle

2021-12-22 03:31 UTC, st-minhdao requested changes
Please check my comment

2021-12-22 03:31 UTC, st-minhdao commented on application/app/Http/Controllers/TaskController.php
> +        return view('admin.task.index',compact('tasks'));
thêm space

2021-12-22 03:31 UTC, st-minhdao commented on application/app/Http/Controllers/TaskController.php
> +        if ($task) return redirect()->route('admin.tasks.index')->with('msg', 'Created successfully!');
dùng if thì nhớ đi kèm cặp ngoặc nhọn {}

2021-12-22 03:31 UTC, st-minhdao commented on application/app/Http/Controllers/TaskController.php
> +            if ($task) return redirect()->route('admin.tasks.index')->with('msg', 'Updated successfully!');
thêm cặp ngoặc
tương tự cho những chỗ khác luôn nha em

2021-12-22 03:31 UTC, st-minhdao commented on application/app/Http/Requests/TaskRequest.php
> +            'status' =>'required|numeric',
chỉ lấy số nguyên dương

2021-12-22 03:31 UTC, st-minhdao commented on application/app/Models/Task.php
> +   	public $timestamps = true;
khi em đặt tên bảng và tên Model theo đúng format thì những cái định nghĩa này không cần nữa

2021-12-22 03:31 UTC, st-minhdao commented on application/database/seeders/DatabaseSeeder.php
> +            TaskSeeder::class,
dùng Factory là tốt
sau khi học phần relationship thì em check lại chỗ này để khi tạo 1 user thì sẽ tạo luôn task cho nó

2021-12-22 03:31 UTC, st-minhdao commented on application/resources/views/admin/task/edit.blade.php
> +              <form method="post" action="{{route('admin.tasks.update',['task'=>$task->id])}}" enctype="multipart/form-data">
thêm space vào em ơi

2021-12-22 03:31 UTC, st-minhdao commented on application/vendor/composer/autoload_classmap.php
> +    'App\\Http\\Controllers\\TaskController' => $baseDir . '/app/Http/Controllers/TaskController.php',
sao lại commit được cả vendor lên thế này hè???

2021-12-22 04:31 UTC, st-trampham commented on application/app/Http/Controllers/TaskController.php
> +        if (DB::table('tasks')->find($id)) {
Chỗ này không cần find vì câu delete ở dưới nêú ko có id thì trả về false rồi

2021-12-23 02:45 UTC, st-minhdao approved these changes

2021-12-23 02:45 UTC, merged