practice eloquent ORM
st-tramle/laravel-intern-2111 pull request #3
Opened 2021-12-25 05:12 UTC by st-tramle

2021-12-27 08:02 UTC, st-minhdao requested changes
please check my comments

2021-12-27 08:02 UTC, st-minhdao commented on application/app/Models/Task.php
> +        return $query->findOrFail($id);
scope chỉ khai báo điều kiện chớ không có lấy ra dữ liệu nghe Trâm

2021-12-27 08:02 UTC, st-minhdao commented on application/app/Models/Task.php
> +    }
scope ni cũng được, nhưng đặt tên chưa hợp lý lắm

2021-12-27 15:39 UTC, st-trampham commented on application/app/Http/Controllers/TaskController.php
> +    private TaskRepositoryInterface $taskRepository;
khai báo như này là dc `private $taskRepository;`

2021-12-27 15:39 UTC, st-trampham commented on application/app/Http/Controllers/TaskController.php
> +        $task = $this->taskRepository->getById($id);
Ko cần thiết get task chỗ này

2021-12-27 15:39 UTC, st-trampham commented on application/app/Repositories/TaskRepository.php
> +        Task::destroy($id);
return

2021-12-31 04:24 UTC, st-trampham commented
LGTM!

2021-12-31 04:24 UTC, merged